// Pure helpers for the teaman slides build — theme staging + the slidev CLI
// invocation. Kept side-effect free (no fs writes, no env) so build-slides.mjs
// stays thin and these are unit-testable. See scripts/__tests__/slides-theme.test.mjs.

import { existsSync } from 'fs';
import { isAbsolute, join } from 'path';

/**
 * Build the `slidev build` argv for one deck. The routing flags here are load-
 * bearing — see the long note in build-slides.mjs: a relative `--base` + hash
 * router are what keep in-app nav, deep links and refresh working on a static
 * host (without them Slidev double-applies a sub-path base → /slides/x/slides/x/2
 * 404s). Locked in by a unit test so a future "cleanup" can't silently drop them.
 * @param {string} deckPath  the deck .md to build
 * @param {{ out: string, theme: string }} opts
 * @returns {string[]} argv passed after `npx`
 */
export function slidevBuildArgs(deckPath, { out, theme }) {
  return [
    'slidev', 'build', deckPath,
    '--base', './',
    '--out', out,
    '--theme', theme,
    '--router-mode', 'hash',
  ];
}

// The relative `--base ./` (above) keeps assets path-agnostic, but Slidev's
// getSlidePath bakes BASE_URL into the path it hands to `router.push`:
//   return `${import.meta.env.BASE_URL}${path}`   // -> `./2`, `./presenter/2`
// A *relative* base makes that a relative router path, so navigating from any
// deeper route resolves it against the current depth: `./presenter/2` from
// `/presenter/1` becomes `/presenter/presenter/2` → 404 (presenter mode, and the
// overview's open-in-new-tab). We rewrite the return to an absolute, base-less
// router path (`/2`, `/presenter/2`), which is depth-independent. Asset URLs are
// untouched — Vite emits those from BASE_URL separately. The overview still
// builds full hrefs as `pathPrefix + path.slice(1)` (`./#/` + `2`), resolved by
// the browser relative to the deck dir, so new-tab opens keep working too.
export const GETSLIDEPATH_MARKER = 'return `${import.meta.env.BASE_URL}${path}`';
export const GETSLIDEPATH_REPLACEMENT = 'return `/${path}`';

/**
 * Render the staged `.slides-build/vite.config.ts`. Slidev merges a `vite.config`
 * found in the deck's own directory (resolveSourceFiles over its roots), so this
 * is how we inject the getSlidePath patch above — and the Rolldown `checks` knob
 * that mutes @vueuse/core's harmless INVALID_ANNOTATION noise — without touching
 * node_modules. The transform fails loud if the upstream source no longer contains
 * the marker — a Slidev upgrade that reshapes getSlidePath should break the build
 * visibly, not silently ship broken slide navigation. Guarded by a unit test.
 */
export function renderViteConfig() {
  return `// Generated by build-slides.mjs — do not edit (staged copy).
// Patches @slidev/client's getSlidePath to return an absolute, base-less router
// path so presenter mode and the overview's open-in-new-tab navigate correctly
// under a relative \`--base ./\`. See scripts/slides-theme.mjs for the rationale.
import type { Plugin } from 'vite';

const MARKER = ${JSON.stringify(GETSLIDEPATH_MARKER)};
const REPLACEMENT = ${JSON.stringify(GETSLIDEPATH_REPLACEMENT)};

function patchGetSlidePath(): Plugin {
  return {
    name: 'teaman-slidev-getslidepath',
    enforce: 'pre',
    transform(code, id) {
      if (!id.includes('@slidev/client/logic/slides.')) return;
      if (!code.includes('function getSlidePath')) return;
      if (!code.includes(MARKER)) {
        throw new Error(
          '[teaman] Slidev getSlidePath source changed — the slide-nav patch no ' +
            'longer applies. Re-verify presenter/overview routing and update ' +
            'GETSLIDEPATH_MARKER in scripts/slides-theme.mjs.',
        );
      }
      return code.replace(MARKER, REPLACEMENT);
    },
  };
}

export default {
  plugins: [patchGetSlidePath()],
  build: {
    rollupOptions: {
      // Slidev requires Vite >=8.0.16, whose Rolldown bundler flags
      // \`/* #__PURE__ */\` comments it can't position-resolve in third-party deps
      // — notably @vueuse/core, a Slidev transitive dep — logging a noisy
      // INVALID_ANNOTATION per occurrence. They're harmless dead-code-elimination
      // hints we can't fix upstream, and no Slidev-compatible Vite avoids them, so
      // we disable just this one Rolldown check. Every other check stays on.
      checks: { invalidAnnotation: false },
    },
  },
};
`;
}

// Accent fallbacks — must match the committed slidev-theme-teaman/styles/vars.css
// so the theme looks identical whether or not a vault sets `slides` colours.
export const DEFAULT_SLIDE_PRIMARY = 'oklch(0.62 0.15 48)';
export const DEFAULT_SLIDE_SECONDARY = 'oklch(0.58 0.05 196)';

/**
 * Render the theme's vars.css from the `slides` config. Only the two accents are
 * configurable; the paper/near-black surfaces are fixed so decks always match
 * the site. Output is byte-identical to the committed vars.css when given the
 * defaults.
 * @param {{ primary?: string, secondary?: string }} [slides]
 */
export function renderVarsCss(slides = {}) {
  const primary = slides.primary?.trim() || DEFAULT_SLIDE_PRIMARY;
  const secondary = slides.secondary?.trim() || DEFAULT_SLIDE_SECONDARY;
  return `/* Generated by build-slides.mjs from teaman.config.js \`slides\` —
   do not edit (this is the staged copy). */
:root {
  --slidev-theme-primary: ${primary};
  --slidev-theme-secondary: ${secondary};

  --teaman-slide-bg: oklch(0.992 0.004 95);
  --teaman-slide-fg: oklch(0.21 0.03 264);
  --teaman-slide-muted: oklch(0.45 0.02 264);
  --teaman-slide-border: oklch(0.9 0.005 264);
  --teaman-slide-code-bg: oklch(0.965 0.003 264);
}

html.dark {
  --teaman-slide-bg: oklch(0.18 0.004 308);
  --teaman-slide-fg: oklch(0.92 0 0);
  --teaman-slide-muted: oklch(0.7 0 0);
  --teaman-slide-border: oklch(0.3 0 0);
  --teaman-slide-code-bg: oklch(0.24 0.004 308);
}
`;
}

/**
 * Render logo.config.ts for the staged theme: the resolved logo filename and
 * whether the footer strip should render. global-bottom.vue shows the strip only
 * when `showFooter` is true AND there's a logo to sit on it.
 * @param {string|null} filename
 * @param {{ footer?: boolean }} [opts]  footer defaults to true
 */
export function renderLogoConfig(filename, { footer = true } = {}) {
  return `// Generated by build-slides.mjs — do not edit (staged copy).\n` +
    `export const logoFile: string | null = ${JSON.stringify(filename ?? null)}\n` +
    `export const showFooter: boolean = ${JSON.stringify(Boolean(footer))}\n`;
}

/**
 * Resolve a configured slide-logo path to an existing source file, mirroring the
 * site logo's lookup order: absolute, then the staged public dir (TEAMAN_PUBLIC),
 * then the vault's public/, then the vault root.
 * @param {string|null|undefined} logo
 * @param {{ teamanPublic?: string|null, vaultDir: string, exists?: (p: string) => boolean }} opts
 * @returns {string|null}
 */
export function resolveLogoSource(logo, { teamanPublic, vaultDir, exists = existsSync } = {}) {
  if (!logo) return null;
  if (isAbsolute(logo)) return exists(logo) ? logo : null;
  const candidates = [
    teamanPublic && join(teamanPublic, logo),
    join(vaultDir, 'public', logo),
    join(vaultDir, logo),
  ].filter(Boolean);
  return candidates.find(exists) ?? null;
}
